version: "3.9"

services:
  api:
    build:
      context: .
    container_name: formativa-pipeline
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app
    restart: unless-stopped

volumes:
  sqlite_data: